# **Analyzing Financial Statements in Python**

## **The Balance Sheet**

In this chapter, you will learn how to read and interpret a balance sheet and compute and use financial ratios to evaluate a company's performance using information from the balance sheet. Additionally, you'll gain hands-on experience using the powerful pandas data manipulation package to analyze a company's financial ratios and compare them to its peers in the industry.

#### **Match balance sheet items to their class**

Assets are used by the business to create positive economic value. Thus assets reap benefits to the business. Liabilities are future burdens that the business needs to pay off. Assets and liabilities can be further broken down:

Current assets refer to the class of assets that usually reap benefits in one year.
Current liabilities are those burdens that must be paid off in one year.
Non-current assets reap benefits over a period of one year
Non-current liabilities can be paid off over a period of one year.
In this exercise, accounts_receivable, accounts_payable, short_term_loans, long_term_loans, inventory, long_term_investments, and property_plant_equipment have already been loaded for you.

You will identify which balance sheet items are current or non-current assets and liabilities. You will then use them to add up balance sheet items within the correct class to get the total current and non-current assets and liabilities.

In [1]:
accounts_receivable = 1298
accounts_payable = 500
short_term_loans = 3357
long_term_loans = 8000
inventory = 5420
long_term_investments = 7892
property_plant_equipment = 9840

# Add up total current assets
total_current_assets = accounts_receivable + inventory

# Add up total non-current assets
total_non_current_assets = long_term_investments + property_plant_equipment

# Add up total current liabilities
total_current_liab = short_term_loans + accounts_payable

# Add up total non-current liabilities
total_non_current_liab = long_term_loans

#### **Relation of assets, liabilities, and shareholders' equity**


Recall that assets, liabilities, and shareholders' equity are the three main parts of a balance sheet.

Together, their relationship with each other "balances" the balance sheet.

This relationship is helpful to remember when you don't know the value of one of the main parts of a balance sheet! Suppose you have information about a company's assets and shareholders' equity. You can use your knowledge about their relationship to determine the company's liability.

In this exercise, you will practice doing just this!

In [2]:
current_assets = 1500
non_current_assets = 3000
shareholders_equity = 1200

# Compute total liabilities
total_liabilities = current_assets + non_current_assets - shareholders_equity

#### **Practice using the main equation of accounting**


In this exercise, you'll compute a company's total liabilities using the main accounting equation you've mastered. To do this, you will first have to compute total assets.

accounts_receivable, inventory, long_term_investments and property_plant_equipment are already loaded for you.

You will identify which items of the balance sheet provided are current or non-current assets, compute total assets, and then use the main accounting equation to compute total liabilities.

In [3]:
accounts_receivable = 1356
long_term_investments = 7892
property_plant_equipment = 9840
inventory = 5420
shareholders_equity = 8000

# Add up total current assets
total_current_assets = accounts_receivable + inventory

# Add up total non-current assets
total_non_current_assets = long_term_investments + property_plant_equipment

# Compute total assets
total_assets = total_current_assets + total_non_current_assets

# Compute total liabilities
total_liabilities = total_assets - shareholders_equity

#### **Compute the current ratio**


Recall that the current ratio is a liquidity ratio that measures a company's ability to meet its short-term financial burdens.

In this exercise, some items from the balance sheet have been defined for you as variables. You will assess these items and use them to compute the current ratio.

In [4]:
accounts_receivable = 1298
accounts_payable = 500
short_term_loans = 3357
long_term_loans = 8000
inventory = 5420
long_term_investments = 7892
property_plant_equipment = 9840

# Compute the current ratio
current_ratio = (accounts_receivable + inventory) / (accounts_payable + short_term_loans)
print(current_ratio)

1.741768213637542

#### **Leverage ratios**


Leverage ratios are a measure of how much equity and debt is used by the company in running its operations. Running a company with too much debt might sound bad initially, but if it makes enough cash inflows (more on this in the third chapter) to pay off its debts, having a lot of debt is not necessarily bad. Similarly, having too much equity is not necessarily as beneficial as one might think. It might be inefficient because a company could be borrowing more money to grow its operations.

In this exercise, you'll compute the debt-to-equity and equity multiplier ratios. Relevant items from the balance sheet have already been defined for you as variables.

You will first use these to compute total assets, liabilities, and shareholders' equity. You'll then use these values to compute the debt-to-equity and equity multiplier ratios.

In [5]:
accounts_receivable = 1298
accounts_payable = 500
short_term_loans = 3357
long_term_loans = 8000
inventory = 5420
long_term_investments = 7892
property_plant_equipment = 9840

# Compute total assets
total_assets = inventory + accounts_receivable + property_plant_equipment + long_term_investments

# Compute total liabilities
total_liabilities = accounts_payable + short_term_loans + long_term_loans

# Compute total shareholders' equity
shareholders_equity = total_assets - total_liabilities

In [6]:
total_assets = 24450
total_liabilities = 11857
shareholders_equity = 12593

# Compute debt-to-equity ratio
debt_to_equity = total_liabilities / shareholders_equity
# Compute equity multiplier ratio
equity_multiplier = total_assets / shareholders_equity

print(f"Debt-to-equity ratio: {debt_to_equity}")
print(f"Equity multiplier ratio: {equity_multiplier}")

Debt-to-equity ratio: 0.9415548320495514
Equity multiplier ratio: 1.9415548320495513

#### **Compute current and debt-to-equity ratios**


You just learned about liquidity ratios. In this exercise, you'll compute the current ratio, a liquidity ratio, to assess the company's assets to meet its short-term commitments. You'll also compute the debt-to-equity ratio, a commonly used leverage ratio, to see whether a company runs its operations using more debt or its "own" funds.

A pandas DataFrame balance_sheet has been loaded for you. pandas with alias pd has been loaded for you.

In [7]:
import pandas as pd

In [11]:
balance_sheet = pd.read_excel('balance_sheet.xlsx')

In [12]:
# Print the columns in df_bal_sheet
print(balance_sheet.columns)

Index(['Year', 'Accounts Payable', 'Cash', 'Common Stock',
       'Gains Losses Not Affecting Retained Earnings', 'Inventory',
       'Long Term Debt', 'Long Term Investments', 'Net Receivables',
       'Net Tangible Assets', 'Other Assets', 'Other Current Assets',
       'Other Current Liab', 'Other Liab', 'Other Stockholder Equity',
       'Property Plant Equipment', 'Retained Earnings', 'Short Long Term Debt',
       'Short Term Investments', 'Total Assets', 'Total Current Assets',
       'Total Current Liabilities', 'Total Liab', 'Total Stockholder Equity',
       'comp_type', 'company', 'Deferred Long Term Asset Charges', 'Good Will',
       'Intangible Assets', 'Capital Surplus', 'Minority Interest',
       'Deferred Long Term Liab'],
      dtype='object')

In [13]:
# Compute the current ratio
balance_sheet["current_ratio"] = balance_sheet['Total Current Assets'] / balance_sheet['Total Current Liabilities']

# Compute debt-to-equity ratio
balance_sheet["debt_to_equity"] = balance_sheet['Total Liab'] / balance_sheet['Total Stockholder Equity']

In [14]:
balance_sheet.head()

,Year,Accounts Payable,Cash,Common Stock,Gains Losses Not Affecting Retained Earnings,Inventory,Long Term Debt,Long Term Investments,Net Receivables,Net Tangible Assets,...,comp_type,company,Deferred Long Term Asset Charges,Good Will,Intangible Assets,Capital Surplus,Minority Interest,Deferred Long Term Liab,current_ratio,debt_to_equity
0,2019,46236000000,48844000000,4.517400e+10,-584000000,4.106000e+09,9.180700e+10,1.053410e+11,45804000000,90488000000,...,tech,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,1.540126,2.741004
1,2020,42296000000,38016000000,5.077900e+10,-406000000,4.061000e+09,9.866700e+10,1.008870e+11,37445000000,65339000000,...,tech,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,1.363604,3.957039
2,2021,54763000000,34940000000,5.736500e+10,163000000,6.580000e+09,1.091060e+11,1.278770e+11,51506000000,63090000000,...,tech,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,1.074553,4.563512
3,2022,64115000000,23646000000,6.484900e+10,-11109000000,4.946000e+09,9.895900e+10,1.208050e+11,60932000000,50672000000,...,tech,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,0.879356,5.961537
4,2019,9382000000,11356000000,7.852000e+10,-340000000,2.063000e+09,6.666200e+10,2.649000e+09,29524000000,52554000000,...,tech,MSFT,7.536000e+09,4.202600e+10,7.750000e+09,NaN,NaN,NaN,2.528839,1.800313

#### **Compute relative difference by industry**


Computing the relative difference between a company's ratio and its industry average is an excellent way to see if a company is at par with its peers. In this exercise, you'll practice computing the relative difference of the equity multiplier ratio of various FMCG companies from their industry average.

A pandas DataFrame balance_sheet has been loaded for you. pandas has been loaded for you under the alias pd. You can call balance_sheet.columns in the console to assess which columns you can use for the exercise.

In [16]:
# Subset the fmcg companies
fmcg = balance_sheet[balance_sheet["comp_type"]=="fmcg"]
fmcg
# Compute equity multiplier ratio
fmcg["equity_multiplier_ratio"] = fmcg["Total Assets"] / fmcg["Total Stockholder Equity"]

# Compute average equity multiplier ratio by year
fmcg["average_equity_multiplier_ratio"] = fmcg.groupby("Year")["equity_multiplier_ratio"].transform("mean")

# Compute the relative difference
fmcg["relative_difference"] = (fmcg["equity_multiplier_ratio"] / fmcg["average_equity_multiplier_ratio"]) - 1

fmcg[["Year", "company", "relative_difference"]]

<ipython-input-16-8429b6b1b2fa>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fmcg["equity_multiplier_ratio"] = fmcg["Total Assets"] / fmcg["Total Stockholder Equity"]
<ipython-input-16-8429b6b1b2fa>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fmcg["average_equity_multiplier_ratio"] = fmcg.groupby("Year")["equity_multiplier_ratio"].transform("mean")
<ipython-input-16-8429b6b1b2fa>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fmcg["relative_difference"] = (fmcg["equity_multiplier_ratio"] / fmcg["average_equity_multiplier_ratio"]) - 1

    Year company  relative_difference
40  2018   NSRGY            -0.469195
41  2019   NSRGY            -0.376656
42  2020   NSRGY            -0.360493
43  2021   NSRGY            -0.328284
44  2019      PG            -0.369317
45  2020      PG            -0.376684
46  2021      PG            -0.327446
47  2022      PG             0.000000
48  2018     PEP             0.188564
49  2019     PEP             0.346777
50  2020     PEP             0.627206
51  2021     PEP             0.477159
52  2018      UL             0.191593
53  2019      UL             0.245436
54  2020      UL             0.044226
55  2021      UL             0.126124
56  2018      KO             0.089037
57  2019      KO             0.153761
58  2020      KO             0.065746
59  2021      KO             0.052447

#### **Compute ratios by industry**


In this exercise, you will assess how the current ratio and debt-to-equity ratio of Tech and FMCG companies are different on average and over time.

An industry's ratio, on average gives us an overall idea of the industry's financial condition. On the other hand, an industry's ratio over timehelps us understand its trends: is the ratio relatively stable or fluctuating over time? Is it improving or worsening?

balance_sheet has been loaded for you as a pandas DataFrame. The current ratio is provided in a column called curr_ratio, and the debt-to-equity ratio is provided in a column called debt_to_equity. pandas has been loaded with the alias pd.

In [17]:
# Choose the tech and fmcg companies
tech_fmcg = balance_sheet.loc[balance_sheet["comp_type"].isin(["tech","fmcg"])]

# Compute the average debt-to-equity ratio and current ratio by industry
groupby_industry = tech_fmcg.groupby("comp_type")[["current_ratio", "debt_to_equity"]].mean()

# Compute the average debt-to-equity ratio and current ratio by industry and over time
groupby_industry_time = tech_fmcg.groupby(["comp_type", "Year"])[["current_ratio", "debt_to_equity"]].mean()

groupby_industry

           current_ratio  debt_to_equity
comp_type
fmcg            0.868631        2.997896
tech            2.561735        1.777448

In [18]:
groupby_industry_time

                current_ratio  debt_to_equity
comp_type Year
fmcg      2018       0.894033        3.447528
          2019       0.801619        2.901630
          2020       0.958568        3.181890
          2021       0.868201        2.842454
          2022       0.654545        1.537927
tech      2018       4.070359        1.067458
          2019       2.587904        1.572071
          2020       2.609484        1.724153
          2021       2.074543        1.742648
          2022       1.331981        3.576108